### ISSUE TITLE
[Bug] Macro System does not execute

### ISSUE THREAD

**Issue by Imper1um** [Imper1um/foundry-ceus#32]
**Required Information**
Please include this information to help us track down the issue.
- Browser: Chrome/Opera GX
- Operating System: Windows 10
- Foundry Version: v11.311
- Ruleset System (sf1e, pf1, etc.): sf1e
- Ruleset System Version:
- Ceus Version: v0.85

**Description**
Macro System does not execute correctly when creating Macros

**Reproduction Steps**
How do developers reproduce the bug? Please give exact steps:
1. Create any roll
2. Execute Macro

**Helpful Information**
- Foundry Warnings/Errors: Uncaught (in promise) ReferenceError: Ceus is not defined
    at Macro.eval (eval at #executeScript (foundry.js:22842:16), <anonymous>:15:4)
    at #executeScript (foundry.js:22846:17)
    at Macro.execute (foundry.js:22794:35)
    at MacroConfig._onExecute (foundry.js:75447:17)

**Comment by Imper1um** [comment]
Fixed #33
